name: first-ci
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v4

      - name: list files
        run: ls -la

      - name: reed readme
        run: cat REDME.md